#!/usr/bin/env sh

pydnsadm_add() {
  fulldomain=$1
  txtvalue=$2

  if [ "$bkey" ]; then
    _saveaccountconf_mutable pydns_api_key "$pydns_api_key"
  else
    _err "You did not provide a pydns_api_key; please review  pydnsadm user guide again."    
    return 1
  fi

  if [ "$pydns_api_url" ]; then
    _saveaccountconf_mutable pydns_api_url "$pydns_api_url"
  else
    _err "You did not provide a proper pydns_api_url; please review  pydnsadm user guide again."
    return 1

  fi

  _info "Adding record $fulldomain"
  export _H1="X-Api-Key: $pydns_api_key"
  export _H2="Content-Type: application/json"
  data="{\"response\":\"$txtvalue\",\"rrtype\":\"TXT\",\"ttl\":30}"
  _debug "data: $data"
  response="$(_post "$data" "$pydns_api_url/dns/record/$fulldomain")"
  _debug "got response: $response"
}

pydnsadm_rm() {
  fulldomain=$1
  txtvalue=$2

  if [ "$pydns_api_key" ]; then
    _saveaccountconf_mutable bindrestapi_key "$pydns_api_key"
  else
    _err "You did not provide a bindrestapi_key; please review the documentation again"
    return 1
  fi

  if [ "$pydns_api_url" ]; then
    _saveaccountconf pydns_api_url "$pydns_api_url"
  else
    _err "You did not provide a pydns_api_url; please review the documentation again  "
    return 1
  fi

  _info "deleting record $fulldomain"
  export _H1="X-Api-Key: $pydns_api_key"
  export _H2="Content-Type: application/json"
  data="{\"response\":\"$txtvalue\",\"rrtype\":\"TXT\",\"ttl\":30}"
  _debug "data: $data"
  response="$(_post "$data" "$pydns_api_url/dns/record/$fulldomain" "" "DELETE")"
  _debug "got response: $response"
}
